version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alumind-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: alumind
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: