version: '3.8'

services:
  db:
    image: postgres:17  # Usa a imagem oficial do PostgreSQL
    container_name: postgres_db
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=alumind
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile  # Dockerfile da aplicação Spring Boot
    container_name: spring_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/alumind
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8080:8080"  # Mapeia a porta 8080 para acessar a aplicação
    depends_on:
      - db  # Define que a aplicação espera o serviço db estar pronto antes de iniciar

volumes:
  db_data:
